FROM jenkins/agent:alpine-jdk21

USER root

RUN apk add python3

RUN apk add py3-pip pipx

RUN python3 --version

# Ensure pipx installs globally in /opt
ENV PIPX_BIN_DIR="/opt/poetry/bin"
ENV PIPX_HOME="/opt/poetry"

# Install Poetry using pipx
RUN pipx install poetry

# Ensure Poetry is in the global PATH
ENV PATH="${PIPX_BIN_DIR}:${PATH}"

# Change ownership so Jenkins user can access Poetry
RUN chown -R jenkins:jenkins /opt/poetry

# Verify Poetry installation as root
RUN poetry --version

# Switch to Jenkins user
USER jenkins

# Verify Poetry installation as Jenkins user
RUN poetry --version

RUN poetry config virtualenvs.create false